# This is the config file for testing SmartSea MSP toolbox server with Travis-ci.org

language: perl
perl:
  - "5.16"

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo add-apt-repository ppa:johanvdw/gdal
  - sudo apt-get update
  - sudo apt-get install sqlite3 libgd2-noxpm-dev npm phantomjs libgdal-dev
  - sudo npm install -g eslint

env:
  - PERL_GDAL_NO_VERSION_CHECK=1

install:
  - cpanm -v --installdeps --notest . 

script: "make test"

branches:
  only:
    - master

notifications:
  recipients:
    - ari.jolma@gmail.com
  email:
    on_success: change
    on_failure: always
